### ISSUE TITLE
tidyr::extract(), a separate() with regex

### ISSUE THREAD

**Issue by xvrdm** [rdboyes/adventofcode2020#1]
https://github.com/rdboyes/adventofcode2020/blob/03e99a3e3a2aa0c2acd5fceb43eb957f39fbfba0/day2.Rmd#L163

Don't mean to intrude and you might know it already, but have a look at `tidyr::extract()` if you haven't. It's perfect for this :)

**Comment by rdboyes** [comment]
That's super useful, thanks! The whole reason to do these types of challenges is to run into little useful functions like that :) (and for fun, of course)
